### ISSUE TITLE
Update to Run on ASP.NET 5

### ISSUE THREAD

**Issue by Chaddeus** [JudahGabriel/RavenDB.AspNet.Identity#10]
As ASP.NET 5 has an RC out, what would it take to get RavenDB.AspNet.Identity to run on DNX Core 5?

**Comment by JudahGabriel** [comment]
We've implemented a RavenDB Identity Provider for .NET Core in a separate repo: [RavenDB.Identity](https://github.com/JudahGabriel/RavenDB.Identity).
