### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by phinett** [JudahGabriel/RavenDB.AspNet.Identity#11]
Any plans to update this to support .NET Core 1.0 now that the RavenDb client supports it?

**Comment by JudahGabriel** [comment]
Working on it now, should have something available today.

**Comment by JudahGabriel** [comment]
OK, .NET Core supported: [RavenDB.AspNetCore.Identity](https://github.com/JudahGabriel/RavenDB.AspNet.Identity/tree/master/RavenDB.AspNetCore.Identity).

It's not published to NuGet just yet, as I'm sorting out some naming questions with Hibernating Rhinos. The NuGet package for that should be released by this weekend.

**Comment by JudahGabriel** [comment]
I've moved the RavenDB .NET Core identity provider over to its own repository: [RavenDB.Identity](https://github.com/JudahGabriel/RavenDB.Identity). It's published on NuGet as RavenDB.Identity.
