### ISSUE TITLE
RavenDb 4

### ISSUE THREAD

**Issue by joaomatossilva** [JudahGabriel/RavenDB.AspNet.Identity#13]
Any plans to upgrade to RavenDb 4?

**Comment by JudahGabriel** [comment]
Fixed. I've updated the library to Raven 4, and added a sample MVC application that uses it. I've updated the NuGet package as well, it should be listed within the hour.

**Comment by joaomatossilva** [comment]
Great (tho I've already starting migrating my app to Core 😃  )

**Comment by JudahGabriel** [comment]
Sweet. I recommend AspNetCore + Raven + [Raven.Identity](https://github.com/JudahGabriel/RavenDB.Identity). I'm using that stack myself and it's quite wonderful.
