### ISSUE TITLE
Support for ASP.NET Identity in vNext

### ISSUE THREAD

**Issue by marcuslindblom** [JudahGabriel/RavenDB.AspNet.Identity#5]
Are there any plans on updating your provider and support vNext?

**Comment by dzolnjan** [comment]
Has anyone made progress porting to vnext mvc project?

**Comment by John0x** [comment]
Doesn't seem like it, sadly.

**Comment by JudahGabriel** [comment]
I'm planning on porting it when the vNext bits are final. Right now we're still in RC mode.

**Comment by JudahGabriel** [comment]
I've updated this repo to work on the latest ASP.NET MVC and WebAPI.

If you're running on .NET Core, we've built a RavenDB Identity Provider for .NET Core: see the [RavenDB.Identity repo](https://github.com/JudahGabriel/RavenDB.Identity).
